Make AddKeyUp handle VirtualKeyCode.NUMPAD_RETURN correctly.
GregsStack/InputSimulatorStandard pull request #125
Opened 2022-01-02 06:34 UTC by maimedleech

Key up for this extended key code was not working with at least one target app (the game Elite Dangerous). This change makes AddKeyUp work like AddKeyDown, and that fixed the issue.

2022-01-03 09:13 UTC, Gh0stWalk3r commented
Hello @maimedleech 
Thanks a lot for spotting the issue and providing a PR for it.
Unfortunately I can't merge it at the current state as it will change the `TargetFrameworks`, which is at the moment not intended for this project.
If you are so kind to revert those changes, I am willing to merge it 😄

2022-01-03 09:18 UTC, Gh0stWalk3r requested changes

2022-01-03 09:18 UTC, Gh0stWalk3r commented on src/GregsStack.InputSimulatorStandard/GregsStack.InputSimulatorStandard.csproj
> +    <TargetFrameworks>net5.0;net6.0;netcoreapp3.1</TargetFrameworks>
Please revert changes to `TargetFrameworks` as it will break compatibility with older applications.

2022-01-04 01:20 UTC, maimedleech commented
Sorry about that. Replaced with a PR from a different branch.

2022-01-04 01:20 UTC, closed without merging